Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [4]:
import numpy as np
from numpy import linalg

In [5]:
n = 10
np.arange(0, n)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [14]:
new_matrix = np.diag(np.arange(0, n)[::-1], k=0)
print('Сумма значений на диагонали:', np.arange(0, n)[::-1].sum())

Сумма значений на диагонали: 45


In [15]:
new_matrix

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [26]:
x = np.array( [[4, 2, 1], [1, 3, 0], [0, 5, 4]] )
y = np.array( [4, 12, -3])
linalg.solve(x, y)

array([ 0.46666667,  3.84444444, -5.55555556])

Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем. Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats.

In [18]:
users_stats = [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ]

In [19]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [28]:
distance = {}
next_user_stats_val = np.linalg.norm(next_user_stats)
for i, user in enumerate(users_stats, 1):
    user_val = np.linalg.norm(user)
    distance[i] = np.dot(next_user_stats, user) / (next_user_stats_val * user_val)
distance

{1: 0.19999999999999996,
 2: 0.8451542547285165,
 3: 0.3999999999999999,
 4: 0.7905694150420948,
 5: 0.3999999999999999,
 6: 0.0,
 7: 0.0,
 8: 0.9486832980505138,
 9: 0.0,
 10: 0.0}

In [29]:
i = 0
max_similarity = 0
for vector in users_stats:
    i+=1
    b = users_stats[i-1]
    if distance[i] > max_similarity:
        max_similarity = distance[i]
        max_similarity_n = i
    
print('Самый похожий пользователь: id', max_similarity_n)

Самый похожий пользователь: id 8
